# Generated by Django 3.1.1 on 2020-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
