# Generated by Django 3.1.1 on 2020-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201008_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_id',
            field=models.IntegerField(null=True, verbose_name='Winner'),
        ),
    ]
