# Generated by Django 3.1.1 on 2020-10-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_winner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
